FROM python:3.13.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /app

ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONPATH="/app"

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-dev --extra cloud

COPY src/ src/
COPY pipelines/ pipelines/
COPY .secrets/ .secrets/