id: orchestrate_gpu_pipeline
namespace: deng_midterm

tasks:
  - id: run_ingestion_container
    type: io.kestra.plugin.docker.Run
    containerImage: gpu_pipeline:latest
    pullPolicy: NEVER
    networkMode: gpu_data_network
    env:
      DB_USER: admin
      DB_PASSWORD: adminpassword
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: gpu_database

triggers:
  - id: daily_batch_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 2 * * *"
    backfill:
      start: 2026-03-01T00:00:00Z